# Generated by Django 4.2.23 on 2025-06-12 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme_name', models.CharField(choices=[('minimal', 'Minimal'), ('warm', 'Warm'), ('dark', 'Dark')], default='minimal', max_length=20)),
                ('primary_color', models.CharField(default='blue', max_length=20)),
                ('font_choice', models.CharField(choices=[('sans', 'Sans-serif'), ('serif', 'Serif'), ('mono', 'Monospace')], default='sans', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
