# Generated by Django 4.2.7 on 2025-06-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('featured_products', 'Featured Products'), ('text_block', 'Text Block'), ('testimonials', 'Testimonials'), ('contact_form', 'Contact Form'), ('image_gallery', 'Image Gallery')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_blocks', to='stores.store')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('store', 'block_type', 'order')},
            },
        ),
    ]
