# Generated by Django 4.2.23 on 2025-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_add_custom_css_js_theme_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='custom_js',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='theme_version',
            field=models.CharField(default='v1', max_length=10),
        ),
    ]
