# Generated by Django 4.2.23 on 2025-06-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_slug'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
    ]
