# Generated by Django 4.2.23 on 2025-06-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_slug'),
        ('products', '0003_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
            preserve_default=False,
        ),
    ]
