# Generated by Django 4.2.23 on 2025-06-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_stock_is_featured'),
        ('products', '0004_alter_product_store'),
    ]

    operations = [
    ]
